// <auto-generated>
//   Written by tools~/gen_builtin_icons.py. Do not edit by hand: change the
//   generator and re-run it. tools~/verify.sh fails when this file is stale.
// </auto-generated>
//
// The built-in Android shortcut icons as VectorDrawable XML. On Android an
// IconType is resolved BY NAME at runtime — QuickActionsBridge.java tries the
// project's ic_quickaction_<name> first, then ic_quickaction_builtin_<name> —
// so the drawable has to exist in the app, and the build post-processor writes
// these into the generated Gradle project under the second prefix. Vectors,
// so one density-independent file per icon; embedded rather than shipped as
// assets so a Git/OpenUPM install and a .unitypackage one deliver the same
// bytes with no package-path resolution, and so the headless harness can hold
// the post-processor to this source of truth byte for byte.
//
// 48dp on a 96 viewport, white glyph on a #3F51B5 disc.
namespace EminDeniz99.QuickActions.Editor
{
    internal static class QuickActionsBuiltInIcons
    {
        internal sealed class Entry
        {
            /// <summary>The catalog value this drawable renders.</summary>
            public readonly IconType Icon;
            /// <summary>The &lt;name&gt; in ic_quickaction_builtin_&lt;name&gt; — must equal
            /// the Java ICON_NAMES entry for <see cref="Icon"/>'s value.</summary>
            public readonly string Name;
            /// <summary>The VectorDrawable, verbatim.</summary>
            public readonly string Xml;

            public Entry(IconType icon, string name, string xml)
            {
                Icon = icon;
                Name = name;
                Xml = xml;
            }
        }

        /// <summary>The res/ subdirectory the entries are written under: a vector is
        /// density-independent, so the unqualified one.</summary>
        internal const string ResourceDirectory = "drawable";
        /// <summary>The viewport every entry draws on (width and height).</summary>
        internal const int Viewport = 96;

        internal static readonly Entry[] Entries =
        {
            new Entry(IconType.Add, "add",
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<!-- Written by com.emindeniz99.quick-actions (tools~/gen_builtin_icons.py). A\n" +
                "     project's own ic_quickaction_<name> takes precedence over this file. -->\n" +
                "<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n" +
                "    android:width=\"48dp\"\n" +
                "    android:height=\"48dp\"\n" +
                "    android:viewportWidth=\"96\"\n" +
                "    android:viewportHeight=\"96\">\n" +
                "  <path\n" +
                "      android:fillColor=\"#3F51B5\"\n" +
                "      android:pathData=\"M2,48A46,46 0 1,1 94,48A46,46 0 1,1 2,48Z\" />\n" +
                "  <path\n" +
                "      android:fillColor=\"#FFFFFF\"\n" +
                "      android:pathData=\"M44,24L53,24L53,73L44,73ZM24,44L73,44L73,53L24,53Z\" />\n" +
                "</vector>\n"),
            new Entry(IconType.Compose, "compose",
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<!-- Written by com.emindeniz99.quick-actions (tools~/gen_builtin_icons.py). A\n" +
                "     project's own ic_quickaction_<name> takes precedence over this file. -->\n" +
                "<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n" +
                "    android:width=\"48dp\"\n" +
                "    android:height=\"48dp\"\n" +
                "    android:viewportWidth=\"96\"\n" +
                "    android:viewportHeight=\"96\">\n" +
                "  <path\n" +
                "      android:fillColor=\"#3F51B5\"\n" +
                "      android:pathData=\"M2,48A46,46 0 1,1 94,48A46,46 0 1,1 2,48Z\" />\n" +
                "  <path\n" +
                "      android:fillColor=\"#FFFFFF\"\n" +
                "      android:pathData=\"M28,70L32,56L60,28L72,40L44,68Z\" />\n" +
                "</vector>\n"),
            new Entry(IconType.Favorite, "favorite",
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<!-- Written by com.emindeniz99.quick-actions (tools~/gen_builtin_icons.py). A\n" +
                "     project's own ic_quickaction_<name> takes precedence over this file. -->\n" +
                "<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n" +
                "    android:width=\"48dp\"\n" +
                "    android:height=\"48dp\"\n" +
                "    android:viewportWidth=\"96\"\n" +
                "    android:viewportHeight=\"96\">\n" +
                "  <path\n" +
                "      android:fillColor=\"#3F51B5\"\n" +
                "      android:pathData=\"M2,48A46,46 0 1,1 94,48A46,46 0 1,1 2,48Z\" />\n" +
                "  <path\n" +
                "      android:fillColor=\"#FFFFFF\"\n" +
                "      android:pathData=\"M48,14L39.18,35.86L15.66,37.49L33.73,52.64L28.02,75.51L48,63L67.98,75.51L62.27,52.64L80.34,37.49L56.82,35.86Z\" />\n" +
                "</vector>\n"),
            new Entry(IconType.Play, "play",
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<!-- Written by com.emindeniz99.quick-actions (tools~/gen_builtin_icons.py). A\n" +
                "     project's own ic_quickaction_<name> takes precedence over this file. -->\n" +
                "<vector xmlns:android=\"http://schemas.android.com/apk/res/android\"\n" +
                "    android:width=\"48dp\"\n" +
                "    android:height=\"48dp\"\n" +
                "    android:viewportWidth=\"96\"\n" +
                "    android:viewportHeight=\"96\">\n" +
                "  <path\n" +
                "      android:fillColor=\"#3F51B5\"\n" +
                "      android:pathData=\"M2,48A46,46 0 1,1 94,48A46,46 0 1,1 2,48Z\" />\n" +
                "  <path\n" +
                "      android:fillColor=\"#FFFFFF\"\n" +
                "      android:pathData=\"M34,26L34,70L72,48Z\" />\n" +
                "</vector>\n"),
        };
    }
}
