// <auto-generated>
//   Written by tools~/gen_builtin_icons.py. Do not edit by hand: change the
//   generator and re-run it. tools~/verify.sh fails when this file is stale.
// </auto-generated>
//
// The built-in Android shortcut icons as PNG bytes. On Android an IconType is
// resolved BY NAME at runtime — getIdentifier("ic_quickaction_" + name) in
// QuickActionsBridge.java — so the drawable has to exist in the app, and the
// build post-processor writes these into the generated Gradle project. They
// are embedded rather than shipped as assets so a Git/OpenUPM install and a
// .unitypackage one deliver the same bytes with no package-path resolution,
// and so the headless harness can hold the post-processor to this source of
// truth byte for byte.
//
// 96x96 RGBA, one density bucket (drawable-xhdpi), white glyph on a #3F51B5 disc.
namespace EminDeniz99.QuickActions.Editor
{
    internal static class QuickActionsBuiltInIcons
    {
        internal sealed class Entry
        {
            /// <summary>The catalog value this drawable renders.</summary>
            public readonly IconType Icon;
            /// <summary>The &lt;name&gt; in ic_quickaction_&lt;name&gt; — must equal the
            /// Java ICON_NAMES entry for <see cref="Icon"/>'s value.</summary>
            public readonly string Name;
            private readonly string _base64;

            public Entry(IconType icon, string name, string base64)
            {
                Icon = icon;
                Name = name;
                _base64 = base64;
            }

            /// <summary>The PNG, decoded fresh on every call.</summary>
            public byte[] Bytes => System.Convert.FromBase64String(_base64);
        }

        /// <summary>Pixel width and height of every entry.</summary>
        internal const int PixelSize = 96;
        /// <summary>The res/ qualifier the entries are written under.</summary>
        internal const string DensityQualifier = "xhdpi";

        internal static readonly Entry[] Entries =
        {
            // sha256 3310c0d30de996b90a797ae48ca5ac4fa30ac96543557d9891cb8428bad0a352
            new Entry(IconType.Add, "add",
                "iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAACzklEQVR42u2dzXGDMBBGXQIluAR3" +
                "YEogHVCKO6AESuCUs0pICZRACUTMKJ7EAWIcYH94mtmbsfH3JLSstKvTiUajKW3Xt/c8WhntFq2J" +
                "FqK10foJa9NnmnTNcG2OkssEr5KI/coW0ncD5EH0IlodrdtA9Cnr0m8WRxX9nHrjnqLPwRju5XwU" +
                "4WsFok9Z7RKEAeF9goh/IkveSG/UhnvPLHs0rWHxv7u2ubVeXzkQ/tEq9aMh3uAl2odD8b9s+G8X" +
                "zf5851j8725roU388gDCP1qpRfzqgOLf5wVp8esDi39/Z6DnH20kHPSZr2NOSN4Ogo9bsYef3yH0" +
                "rIt62Ur8zPlL1povaxmTrqdJOQXWEHaZ5Ws+eloEfSmKmq0BQFU8/5mmaT1hjZWsHgD/srOrUINB" +
                "ALWb3m8UwGujQGugzSiA2kXvNwxg2SjQ/NJlGEC1BEAHgPXjRC6inYYBPBct1b7KZRxAbfrx4wBA" +
                "Zz7oZhzAfJDOQsjZAYBqDkAAwOYW5gD0ANjeTC+6eAAwOg9Y2WriBECpfuHFOYDbGIAGALtZY9ID" +
                "cgQgjAFopQTT3rZYsN/NBQXAk64oAAAAAAAAAAAAkAOAGyrshgYA7AYgEIpQGIogGCccjCMcLRyO" +
                "ZkFGemEeAIJLkizK61iUZ1uK8LYUNmZJZ0+yNVF4hzSbc+U357I9XbqYBwkaggkapCjpSFEiSU86" +
                "VZU0VeFkbRK1FZQroFSBcFVFinUIF+ugXI1wuRqNBZsMAVinYBMly4RLllG0T0klXcpWCpetpHCr" +
                "cOFWShevGO2kePdOW00oX2940uUAhx1CDYwEoz2fOUHgmc8xVj9cTZ3H4F45yE0FBI4yVAKCwzyV" +
                "jAaOs1UAggOdAXFg4SdAVErc1i7di3/hZ94f6p1hdOk3ixPtl+dUbZSpE9J35yi9DEiZvJEmidj+" +
                "4TKG9NlbuhbBaTS17RP74dZBQPIbCAAAAABJRU5ErkJggg=="),
            // sha256 2ed324950669baadecc4967c242e64afa3a363b0ff8677abaec09b7f95d05547
            new Entry(IconType.Compose, "compose",
                "iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAADWklEQVR42u2dvW7bMBSF/Qh6BD2C" +
                "3yB6BHXqqi1jH6AdvGUU0M6F1gIZPARGt2jIkgABggLJ0kVDh7ZAAW5dFcpgAte1ZMsWyftzCNzN" +
                "suXvkOIRfy5nMxQUFKLl7M0qs1HYWNhY2qhtNDbanmjcZ5bumu7aDCTHAS8dxHbiqN13Q5At6LmN" +
                "yobxAL0vjPvNXCv01NXGkNCHxOjuJdUCviIAvS8qkUIwAC9TCPsnEudGWqbR3XvC2dE0jOFvWtuM" +
                "W60vBYDfjpJ8a7A3OLfxIBD+S3T/bU7ZzxvB8Ddta04NfqEA/HYUVOCXCuG/9gux4VeK4b++M6Dm" +
                "a2sJSp/5NPoE53YAfHfkIXy+AehBizr3BT8R/pI15ctagk5XUqfsBtYAdlxkUz56GgA9ahQ1mUKA" +
                "BWAeP58wxUwWQJ4WKYYaOA5VoPZHbgUSa//X6x/txcdv9FuBxNrfwX8pkURI1b50bcKPKEI5RgAj" +
                "GX4kEYy60c4h+JFEyNV0vofAjyBCpeLxMwZ+YBGM+EG3Y+AHFiET635OgR9QhHJIgFoz/EAi1EMC" +
                "qIcfQgRRz38f8AOIkIlYauITvmcBCvYTL4zh756ocXtrAT+ME1qydUAC4O92Qhwm3oXAX0/Ys7Og" +
                "guDvtqKAv4IAWuCzEUAqfBYCSIZPXgDp8PsEaAB/FdWG1oAfLGpyQxGK4PcORSwAP+Kq6VjD0Qrh" +
                "9w5HB5+QeXt+rRF+/8R86Bv59PlJI/yWzKT8zd0vdfD3TcoHXZaiEP7eZSnB+oH3F/ca4e/fPRlq" +
                "aeLlVaMRviGzOPfn77/a4B+8ODfnZD8ZwT88mYfvx9BU9pMZfENmi9IU9pMZ/NFblFLK9pMh/PFb" +
                "VX11xqfaT6bwq2P2Caex7OfD4591VF++r+Pdh9t1qEtX4KMVdPZTIGA/WRWRriBysg6kq4mcrgYJ" +
                "mwgkbELKssgpy5C0j0gmXaStjJy2EolbIyduRepiAqmLkbx75FITpK9n3Okiq2KAoQa0BKY1H31C" +
                "hGc+jrH6x2rSPAb3DAe5kRABRxkSEQKHeRJpDTjOloAQONAZQigG3yNEScS2Gncv8sEPvD9UgcUw" +
                "7jfzGcp/zqn0tFOndt+dgfQ4QQrnRpYOYrPHMtbuswt3LYCjoJAtzwfGr5XFmnrPAAAAAElFTkSu" +
                "QmCC"),
            // sha256 b14c9dda981c517b3df469afed064339964721844216660f87062c9dc8dfdc02
            new Entry(IconType.Favorite, "favorite",
                "iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAEw0lEQVR42u1dMavUQBC+n3A/4X7C" +
                "/YNLbxMrG4sDC0vBVovXvTKgtVwrWFwhIli8FK9REB6CNgqmsFBBCKJY2MTMsXmEeMllN7M73252" +
                "YODgcpfdmex8k5nZncUiUqRIoLS5+SKpeVvzWc37mvOai5qrHi7UNXv1G/ptEiWpJ/BMCbFi5lz9" +
                "d1RIR+hpzbuaSwtC7+NS3TOdq9BX6ml0KfQhZdBYVnMR/A5A6H28C1IRHgg+TEXUk1gqb6TylGns" +
                "S589msJj4bdd28S3pz4LQPBdzuBXQz3Adc1XAQq/YZrbGtmfLwMWftttTdGEv52B4Lu8RRG+mL2/" +
                "c//ywJK4IC18Ud/+5cWXA0u/M8zuySe+cftV9ev33wPTZ2kPaXY2//zRu6oh+jwbTFDejviEP33+" +
                "ea0A+gwCzKkLP1/c1STg7ZIwGLdd1LUt4S9RXrIIeLsEAMbtl7VlcKDbBd8ugYCxHVBWgTWIyT1+" +
                "8qHqI/oO6EUt4TQ9MFHNr9//9CqAvgOLoi45FAATz7/38HV1iugapHwCRyYLZkLHwBcYjBteeRtq" +
                "6ILvWAICY/NQBdrTPwS+4GBstgrQkuhD4AsOxvqrAO3pHwO+4GCstwrQcrpjwNcDMM50FFD6CL7g" +
                "YFx6Fe00AV8PwDgNGnyDAGMk82MCvuBgXHoTdCO+fPNtsgLoP8BWQeLU+7l19+LwFDZMdnn39OOB" +
                "nz0vqqv3P655irnRMUvte9IYmvHQ2NpjpbE79YZ0d6aQl0EDp6esPalQqT1HmjPN3cDTyocUYJQe" +
                "PJYgCZ1ozqZpUHb7T0u1nSQPnWiuE81Twl5qQkuRAzTRiebI8IK3tZZ4IVALlWhu1hI1am8te9FU" +
                "KMRc/LWf7AHNBZyngK2WJ2Qj8e47ODOAbW/CnsUFHQvOPr4b0JhtRlOdKWBKTF+KXOQSnCvAF3B2" +
                "VWktooAmwokIzjQml5FTMQU0HhISONNYXFdXiyoACZxtg62OAkTqPyXBWTBxX1h/EXOV9/U0X5xb" +
                "DUXoMsXVXRPdU1ABe6gqaAksoHtCVU1L7nyUIqgdlVIJeY7KBw8rJhK2lKSP9l8aB9iS8r7af2Ec" +
                "yKGKcqUJqkjXNQ5I2n9BHEhgShMl7b8QDpRQxbkosSC04tzUB/tPJYYPzt8eeGpJI9xhHi7M0BT7" +
                "T+Uh7QgmfZ5SDuMIB0qoLUom9v9U3N40z+AIBzKoTXo69p+yVTrRS7pWJ+vmCAdWUNtUdUoBTUpD" +
                "6Dc6pZJwm7VtroIx9r8B2an3GgvSlnHA7LgCW6vglP3vgixH+vMUSFvEAfNTFW2tgj77bzs5PgTS" +
                "FnFg2jH4NhI1U0GWIwV6DKThjquxcWBT1/6bgixH3WoXpJlxgOfAJu4gXWP/uUCWE6SZcYC35wDX" +
                "y1mzMxHpGIEGpBlxgP8kXa5jKwFPMeEem51jK5EObgXvLWC3wQPaYR7eHcYRGzYE0tBhE2ajHr8a" +
                "OWz8as4WVgOHuBIAWpjEJj6xjZWUq4nZBncTG7lBKCG2MgRRRGzmCbIaYjtbAEXEhs5RETMWfI8i" +
                "MhC3tVRjCV/wA+8PO8fKKNU900Wk/zynzNJOnVz9dxIlraeQrfJG9kqIxQmXMVfXnqnfRoFHigRL" +
                "/wDA8oZ4cKQJUQAAAABJRU5ErkJggg=="),
            // sha256 1b3825092b4792d905b78968aa16c6750951a6415e9da876606f8cfc3b88cf76
            new Entry(IconType.Play, "play",
                "iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAADPUlEQVR42u1dMYvUQBjdn5CfsD9h" +
                "/8Glt4mVjUXAwlK4VovtrgxoLWntUolgcSlsrhAOQRsPTGEhghBEsbAZJzB7rOtuzuwleW9m3gdf" +
                "t9nNvjcz3zdvZr5ZLGQyGamd3H2ZWs+tr61X1mvrjXVzwBv3mco90z2bCslhgBcORDOy1+67RcgO" +
                "6Jn10no7AeiHvHW/mcUK+tK1xjlB7yOje5dlLMCXBKAf8jJIIjwAPkwi7J9IXDZiPPXu3ROfM5rG" +
                "Y/C3U9vUt1ZfBAD8rhf0vcG+4Mr6ZYDgb7z7byvmfL4NGPzttDVjAz+PAPhdz1nALyIE/zouoMEv" +
                "Iwb/es6glh9bT4h0zOeICS7bEeD7PZsjz28FdG+KupoK/CTwSdaYk7VEQTekoOyENQE7zNMxh55G" +
                "gB6loiZjELAWmMevJ4yxkiUgb+dLL6SGy/ffzL2H55IqUK1/Y+WLj+bO/dfqBXMLbdv24+dvc/b0" +
                "Xby9ADH277OrT9/NoycX8fUCxKSrz16dfw4hPhRDCGiZCNgMS57Hh5Za7fxf+/L1l3l89jZctRS1" +
                "yjXUurT1wemb8IIxSm4+1rr44NGw1NKKbrexLj48e/7Bf5EOKTmPYV188CBtLfoIqH0mYDs+EKet" +
                "dR8BJgQC2GUNykWXqYxU1kjptppMbWSyRk638DKXkcga630EVDEQQCJrVFQZ0NwEEMga9T4CmtgI" +
                "AMoaDVUKiiYAIWuIALCsIQLAsoYIEAEagkQAWRBWGgpOQzURA0/EJEWApQiJcWAxTnI0WI7Wggx6" +
                "YV5LksAlSS3KcyzKa1sKeFuKNmahT09qayJ4h7Q25+I352p7OrqYhw5oAA9o6IgSxxElHdJDH1XV" +
                "MVXwYW0d1CYoV6BSBeCqiirWAS7WoXI14HI1KthEULBJJcvAJctUtI+kkq7KVoLLVqpwK7hwq0oX" +
                "E5QuVvHugVtNVL7e46CrCxxmkBrUEzxt+YoJgDFf11j9lWpyXoN7oovcKEjQVYYkROgyT5LeoOts" +
                "CYjQhc4iImLgDxBRkKStrXuX8IHvmT+UM5PRut/MFrJ/MqdiopM6tfvuVEgPIyR32UjlQGxuSBlr" +
                "99m1e1aAy2S09gewPhGY3prv1QAAAABJRU5ErkJggg=="),
        };
    }
}
