// <auto-generated>
//   Written by tools~/gen_builtin_icons.py. Do not edit by hand: change the
//   generator and re-run it. tools~/verify.sh fails when this file is stale.
// </auto-generated>
//
// Which IconType members ship a built-in Android drawable — names only, no art.
// The drawables themselves are in Editor/Android/QuickActionsBuiltInIcons.cs,
// whose assembly is UNITY_ANDROID-only; this copy lives in the always-present
// Editor assembly so the settings page can flag, on any active target, which
// catalog entries render blank on Android without a drawable of the project's.
namespace EminDeniz99.QuickActions.Editor
{
    internal static class QuickActionsBuiltInIconSet
    {
        /// <summary>Every member with a built-in Android drawable, in catalog order.</summary>
        internal static readonly IconType[] Icons =
        {
            IconType.Add,
            IconType.Compose,
            IconType.Favorite,
            IconType.Play,
        };

        /// <summary>True when the package writes a drawable for <paramref name="icon"/>
        /// into every Android build; false for <see cref="IconType.None"/> and for the
        /// members that need an ic_quickaction_&lt;name&gt; drawable from the project.</summary>
        internal static bool HasAndroidArt(IconType icon)
        {
            foreach (var builtIn in Icons)
                if (builtIn == icon)
                    return true;
            return false;
        }
    }
}
