// Harness-only tests (same mechanism, and same reason for living under .verify/,
// as AndroidKeepRulesTests.cs: Editor/Android and Editor/NativeGate sit behind
// asmdefs a Unity test assembly cannot reference on every build target, so the
// real source files are compiled straight into the dotnet test assembly).
//
// What they pin. 0.5.0 makes IconType.{Add,Compose,Favorite,Play} render on
// Android with nothing added to the project: the build post-processor writes the
// built-in VectorDrawables (QuickActionsBuiltInIcons, generated by
// tools~/gen_builtin_icons.py) into the generated Gradle project under the
// package's OWN prefix, ic_quickaction_builtin_<name>; the Java bridge tries the
// project's ic_quickaction_<name> first and falls back to that; and the static
// baker references the built-in whenever AndroidDrawable is unset. Three things
// regress SILENTLY here — a build that writes no icons is green and looks exactly
// like 0.4.x's blank squares, a static item that stops referencing its drawable
// is green and blank on the one surface a cold install shows, and a define-off
// build that leaves the files behind ships package art in a production APK — so
// all three ends are held here, plus the rule that made the design safe: the
// package never touches a file it did not write.
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using NUnit.Framework;
using EminDeniz99.QuickActions;
using EminDeniz99.QuickActions.Editor;
using EminDeniz99.QuickActions.Editor.NativeGate;

namespace EminDeniz99.QuickActions.Tests
{
    [TestFixture]
    public class AndroidBuiltInIconsTests
    {
        private const string AndroidNs = "http://schemas.android.com/apk/res/android";
        private const string BuiltInPrefix = "ic_quickaction_builtin_";

        private string _root;

        [SetUp]
        public void CreateProject()
        {
            QuickActionsStaticBuild.ResetForTests();
            _root = Path.Combine(Path.GetTempPath(), "qa-icons-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(UnityLibrary);
        }

        [TearDown]
        public void RemoveProject()
        {
            QuickActionsStaticBuild.ResetForTests();
            QuickActionsBuildPostProcessorAndroid.WriteBuiltInIconsOverrideForTests = null;
            try
            {
                if (Directory.Exists(_root))
                    Directory.Delete(_root, true);
            }
            catch (IOException)
            {
            }
        }

        private string UnityLibrary => Path.Combine(_root, "unityLibrary");

        private string ResDir => Path.Combine(UnityLibrary, "src", "main", "res");

        private string DrawableDir => Path.Combine(ResDir, QuickActionsBuiltInIcons.ResourceDirectory);

        private string OurIcon(string name) => Path.Combine(DrawableDir, BuiltInPrefix + name + ".xml");

        private string ShortcutsFile => Path.Combine(ResDir, "xml", "quickactions_shortcuts.xml");

        private string ManifestPath => Path.Combine(UnityLibrary, "src", "main", "AndroidManifest.xml");

        private void WriteManifest(bool launcher)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(ManifestPath));
            var filter = launcher
                ? "      <intent-filter>\n" +
                  "        <action android:name=\"android.intent.action.MAIN\" />\n" +
                  "        <category android:name=\"android.intent.category.LAUNCHER\" />\n" +
                  "      </intent-filter>\n"
                : "";
            File.WriteAllText(ManifestPath,
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"\n" +
                "    package=\"com.example.app\">\n" +
                "  <application>\n" +
                "    <activity android:name=\"com.unity3d.player.UnityPlayerActivity\">\n" +
                filter +
                "    </activity>\n" +
                "  </application>\n" +
                "</manifest>\n");
        }

        private void RunPostProcessor() =>
            new QuickActionsBuildPostProcessorAndroid()
                .OnPostGenerateGradleAndroidProject(UnityLibrary);

        private static void WriteFile(string path, byte[] contents)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllBytes(path, contents);
        }

        // A project's own drawable, the shape the README's .androidlib recipe
        // produces once Unity has copied it into the export: NESTED under
        // unityLibrary (unityLibrary/<Name>.androidlib/src/main/res/…).
        private string ProjectDrawable(string module, string qualifier, string fileName) =>
            Path.Combine(UnityLibrary, module, "src", "main", "res", qualifier, fileName);

        private string LauncherDrawable(string qualifier, string fileName) =>
            Path.Combine(_root, "launcher", "src", "main", "res", qualifier, fileName);

        private static readonly byte[] UserBytes = Encoding.ASCII.GetBytes("the project's own art");

        // The android:icon of the baked static shortcut with this id, or null when
        // the element carries none. Parsed, not grepped: the attribute is namespaced.
        private string BakedIcon(string shortcutId)
        {
            Assert.IsTrue(File.Exists(ShortcutsFile), "the static set must have been baked");
            var doc = new XmlDocument();
            doc.Load(ShortcutsFile);
            foreach (XmlElement shortcut in doc.GetElementsByTagName("shortcut"))
                if (shortcut.GetAttribute("shortcutId", AndroidNs) == shortcutId)
                    return shortcut.HasAttribute("icon", AndroidNs) ? shortcut.GetAttribute("icon", AndroidNs) : null;
            Assert.Fail("no <shortcut> with id '" + shortcutId + "' in " + ShortcutsFile);
            return null;
        }

        [Test]
        public void WritesEveryBuiltInIcon_Verbatim_WithNoStaticShortcuts()
        {
            // The dynamic-only project is the main case (see the keep-rule tests): a
            // consumer adding every shortcut through QuickActions.Add(...) still gets
            // its icons through the same name lookup, so the write must not hang off
            // the static set. And "written" means the source of truth, verbatim — a
            // re-encoded or truncated file would still resolve by name and draw
            // garbage, or nothing.
            WriteManifest(launcher: true);

            RunPostProcessor();

            foreach (var entry in QuickActionsBuiltInIcons.Entries)
            {
                Assert.IsTrue(File.Exists(OurIcon(entry.Name)), "missing " + OurIcon(entry.Name));
                Assert.AreEqual(entry.Xml, File.ReadAllText(OurIcon(entry.Name)),
                    BuiltInPrefix + entry.Name + " must be the embedded vector, unchanged");
            }
            Assert.AreEqual(QuickActionsBuiltInIcons.Entries.Length,
                Directory.GetFiles(DrawableDir).Length, "nothing else may be written there");
        }

        [Test]
        public void TheCatalogSubsetShipped_IsExactlyTheFourWithArt()
        {
            // The docs promise these four and say the other 25 need the consumer's
            // own drawable. Adding art is welcome — it changes this list AND the docs,
            // which is what this pin is for.
            CollectionAssert.AreEquivalent(
                new[] { IconType.Add, IconType.Compose, IconType.Favorite, IconType.Play },
                QuickActionsBuiltInIcons.Entries.Select(e => e.Icon).ToArray());
        }

        [Test]
        public void EveryEntry_IsAWellFormedVectorDrawable()
        {
            // The XML is generated and embedded as a string; a bad regeneration would
            // not fail to compile, and aapt2 would only reject it on the consumer's
            // build. Pin the shape a VectorDrawable needs: a <vector> root with the
            // android namespace, a 48dp size on the declared viewport, and at least
            // two filled paths (the disc that carries the contrast, and the glyph).
            foreach (var entry in QuickActionsBuiltInIcons.Entries)
            {
                var doc = new XmlDocument();
                doc.LoadXml(entry.Xml);
                var root = doc.DocumentElement;
                Assert.AreEqual("vector", root.Name, entry.Name + ": root element");
                Assert.AreEqual("48dp", root.GetAttribute("width", AndroidNs), entry.Name + ": width");
                Assert.AreEqual("48dp", root.GetAttribute("height", AndroidNs), entry.Name + ": height");
                Assert.AreEqual(QuickActionsBuiltInIcons.Viewport.ToString(),
                    root.GetAttribute("viewportWidth", AndroidNs), entry.Name + ": viewportWidth");
                Assert.AreEqual(QuickActionsBuiltInIcons.Viewport.ToString(),
                    root.GetAttribute("viewportHeight", AndroidNs), entry.Name + ": viewportHeight");
                var paths = root.ChildNodes.OfType<XmlElement>().Where(e => e.Name == "path").ToList();
                Assert.GreaterOrEqual(paths.Count, 2, entry.Name + ": a disc and a glyph, at least");
                foreach (var path in paths)
                {
                    StringAssert.IsMatch("^#[0-9A-F]{6}$", path.GetAttribute("fillColor", AndroidNs),
                        entry.Name + ": every path is filled with an opaque colour");
                    StringAssert.IsMatch("^M.*Z$", path.GetAttribute("pathData", AndroidNs),
                        entry.Name + ": every path is a closed shape");
                }
            }
        }

        [Test]
        public void WritesIcons_EvenWithNoLauncherActivity()
        {
            // Same ordering pin as the keep rule: the icons are written BEFORE the
            // launcher discovery that can end the callback early. A project whose
            // launcher lives where this callback cannot see it still gets its icons.
            WriteManifest(launcher: false);
            RunPostProcessor();
            Assert.IsTrue(File.Exists(OurIcon("play")), "a non-launcher manifest must not skip the icons");

            File.Delete(ManifestPath);
            Directory.Delete(DrawableDir, true);
            RunPostProcessor();
            Assert.IsTrue(File.Exists(OurIcon("play")), "a module with no manifest must not skip the icons");
        }

        [Test]
        public void RunningTwice_LeavesTheSameFiles()
        {
            // Append builds and repeated exports re-run the callback into the same
            // tree; the write must be idempotent, not accumulate.
            WriteManifest(launcher: true);

            RunPostProcessor();
            var first = Directory.GetFiles(DrawableDir).OrderBy(f => f)
                .ToDictionary(f => f, File.ReadAllText);
            RunPostProcessor();
            var second = Directory.GetFiles(DrawableDir).OrderBy(f => f)
                .ToDictionary(f => f, File.ReadAllText);

            CollectionAssert.AreEqual(first.Keys, second.Keys);
            foreach (var pair in first)
                Assert.AreEqual(pair.Value, second[pair.Key], pair.Key + " changed on re-run");
        }

        [Test]
        public void NeverTouchesAProjectsOwnDrawable_WhereverItLives()
        {
            // The rule that makes the design safe. A project may ship its own
            // ic_quickaction_<name> in an .androidlib (nested under unityLibrary once
            // Unity has copied it), have another build callback write one straight
            // into unityLibrary's own res, or carry one in the launcher module — and
            // in an .aar or a Maven dependency this callback cannot even see. So it
            // must not read any of them, overwrite any of them, or decide anything
            // from them: the built-in goes in under its OWN name regardless, and the
            // runtime lookup prefers the project's. Any extension, any density.
            WriteManifest(launcher: true);
            var inOurModule = Path.Combine(ResDir, "drawable-xhdpi", "ic_quickaction_add.png");
            var nested = ProjectDrawable("Icons.androidlib", "drawable-anydpi-v26", "ic_quickaction_play.xml");
            var inLauncher = LauncherDrawable("drawable", "ic_quickaction_favorite.webp");
            WriteFile(inOurModule, UserBytes);
            WriteFile(nested, UserBytes);
            WriteFile(inLauncher, UserBytes);

            RunPostProcessor();

            foreach (var theirs in new[] { inOurModule, nested, inLauncher })
                CollectionAssert.AreEqual(UserBytes, File.ReadAllBytes(theirs), "must be untouched: " + theirs);
            foreach (var entry in QuickActionsBuiltInIcons.Entries)
                Assert.IsTrue(File.Exists(OurIcon(entry.Name)),
                    "the built-in is still written under its own name: " + entry.Name);
            Assert.IsEmpty(Directory.GetFiles(DrawableDir, "ic_quickaction_*")
                    .Where(f => !Path.GetFileName(f).StartsWith(BuiltInPrefix)),
                "the package never writes a file under the project's prefix");
        }

        [Test]
        public void StaticShortcut_WithABuiltInIcon_ReferencesTheBuiltInDrawable()
        {
            // The one surface a cold install shows is the static set, and res/xml can
            // only reference a drawable by name. Before 0.5.0 an Icon without an
            // AndroidDrawable baked NO icon (and warned); now the four built-ins are
            // referenced, under the name the writer above just guaranteed exists.
            WriteManifest(launcher: true);
            QuickActionsStaticBuild.Customize += ctx =>
            {
                foreach (var entry in QuickActionsBuiltInIcons.Entries)
                    ctx.Shortcuts.Add(new QuickActionItem("s_" + entry.Name, "S") { Icon = entry.Icon });
            };

            RunPostProcessor();

            foreach (var entry in QuickActionsBuiltInIcons.Entries)
                Assert.AreEqual("@drawable/" + BuiltInPrefix + entry.Name, BakedIcon("s_" + entry.Name),
                    "IconType." + entry.Icon + " must bake a reference to its built-in drawable");
        }

        [Test]
        public void StaticShortcut_AndroidDrawable_BeatsTheBuiltIn()
        {
            // A static item that wants the project's own art names it explicitly —
            // the baker cannot prefer ic_quickaction_<name> the way the runtime lookup
            // does, because the project's copy may live in an .aar it cannot see and
            // an unresolved @drawable hard-fails aapt2.
            WriteManifest(launcher: true);
            QuickActionsStaticBuild.Customize += ctx =>
                ctx.Shortcuts.Add(new QuickActionItem("mine", "M") { Icon = IconType.Add, AndroidDrawable = "my_icon" });

            RunPostProcessor();

            Assert.AreEqual("@drawable/my_icon", BakedIcon("mine"));
        }

        [Test]
        public void StaticShortcut_WithAnIconThatShipsNoArt_BakesNoReference()
        {
            // 25 catalog values ship no built-in. Referencing @drawable/ic_quickaction_search
            // on the chance the project has one would hard-fail every build that does
            // not; the item bakes without an icon (and the build warns), as before.
            WriteManifest(launcher: true);
            QuickActionsStaticBuild.Customize += ctx =>
                ctx.Shortcuts.Add(new QuickActionItem("find", "F") { Icon = IconType.Search });

            RunPostProcessor();

            Assert.IsNull(BakedIcon("find"), "no built-in exists for Search, so nothing may be referenced");
        }

        [Test]
        public void BuiltInsOff_WritesNothing_RemovesAStaleCopy_AndBakesNoReference()
        {
            // The escape hatch: a project that wants no package art in its APK unticks
            // the setting. Off means off in both directions — nothing written, a copy
            // an earlier build left behind removed (a reused export would otherwise
            // keep shipping it), and the static baker must not reference a drawable
            // that is no longer there, or aapt2 fails the build. The project's own
            // files are as untouchable as ever.
            WriteManifest(launcher: true);
            QuickActionsBuildPostProcessorAndroid.WriteBuiltInIconsOverrideForTests = false;
            var stale = Path.Combine(ResDir, "drawable-xhdpi", BuiltInPrefix + "add.png");
            var theirs = Path.Combine(ResDir, "drawable-xhdpi", "ic_quickaction_add.png");
            WriteFile(stale, new byte[] { 9 });
            WriteFile(theirs, UserBytes);
            QuickActionsStaticBuild.Customize += ctx =>
                ctx.Shortcuts.Add(new QuickActionItem("s_add", "S") { Icon = IconType.Add });

            RunPostProcessor();

            foreach (var entry in QuickActionsBuiltInIcons.Entries)
                Assert.IsFalse(File.Exists(OurIcon(entry.Name)), "nothing may be written when off: " + entry.Name);
            Assert.IsFalse(File.Exists(stale), "a built-in left by an earlier build must be removed");
            CollectionAssert.AreEqual(UserBytes, File.ReadAllBytes(theirs), "the project's file is untouched");
            Assert.IsNull(BakedIcon("s_add"), "with the built-ins off, a static item must not reference one");

            QuickActionsBuildPostProcessorAndroid.WriteBuiltInIconsOverrideForTests = true;
            RunPostProcessor();
            Assert.IsTrue(File.Exists(OurIcon("add")), "back on: written again");
            Assert.AreEqual("@drawable/" + BuiltInPrefix + "add", BakedIcon("s_add"), "back on: referenced again");
        }

        [Test]
        public void Names_MatchTheIconTypeMember_AndTheJavaLookupTable()
        {
            // Three copies of each name: the IconType member (documented rule:
            // snake_case of the member), the generated C# entry, and the Java
            // ICON_NAMES table the runtime lookup indexes by the enum's integer. The
            // Java copy is read from the repository file, which is why this test is
            // harness-only. Drift between them is silent — the drawable is written
            // under one name and looked up under another. The Java fallback must
            // build its name from the same prefix the writer uses, for the same reason.
            var java = File.ReadAllText(Path.Combine(RepoRoot(), "Plugins", "Android", "QuickActionsBridge.java"));
            var table = Regex.Match(java, @"ICON_NAMES\s*=\s*\{([^}]*)\}", RegexOptions.Singleline);
            Assert.IsTrue(table.Success, "could not find ICON_NAMES in QuickActionsBridge.java");
            var javaNames = Regex.Matches(table.Groups[1].Value, "\"([^\"]*)\"")
                .Cast<Match>().Select(m => m.Groups[1].Value).ToArray();

            Assert.AreEqual(BuiltInPrefix, QuickActionsBuildPostProcessorAndroid.BuiltInIconPrefix);
            StringAssert.IsMatch("\"" + BuiltInPrefix + "\"\\s*\\+\\s*ICON_NAMES\\[", java,
                "the Java fallback must concatenate the built-in prefix with the same table");
            foreach (var entry in QuickActionsBuiltInIcons.Entries)
            {
                Assert.AreEqual(SnakeCase(entry.Icon.ToString()), entry.Name,
                    "the generated name must follow IconType's documented snake_case rule");
                Assert.AreEqual(javaNames[(int)entry.Icon], entry.Name,
                    $"ICON_NAMES[{(int)entry.Icon}] in QuickActionsBridge.java disagrees with the generated name");
            }
        }

        private static string SnakeCase(string member)
        {
            var sb = new StringBuilder();
            for (var i = 0; i < member.Length; i++)
            {
                if (i > 0 && char.IsUpper(member[i]))
                    sb.Append('_');
                sb.Append(char.ToLowerInvariant(member[i]));
            }
            return sb.ToString();
        }

        // Walk up from the test binary until the package root (the one directory
        // holding both package.json and Plugins/). The harness always runs from a
        // checkout; a miss is a broken harness, not a skip.
        private static string RepoRoot()
        {
            var dir = new DirectoryInfo(TestContext.CurrentContext.TestDirectory);
            while (dir != null)
            {
                if (File.Exists(Path.Combine(dir.FullName, "package.json")) &&
                    Directory.Exists(Path.Combine(dir.FullName, "Plugins")))
                    return dir.FullName;
                dir = dir.Parent;
            }
            throw new InvalidOperationException("package root not found above " + TestContext.CurrentContext.TestDirectory);
        }

        [Test]
        public void Stripper_RemovesTheBuiltIns_AndOnlyThose_AndOnlyFromUnityLibrary()
        {
            // The define-off cleanup runs in a production build; a reused/exported
            // project must come out of it carrying no package art. It undoes exactly
            // what the writer did — the built-in prefix, in unityLibrary, in any
            // extension (a stale copy from an older art format counts) — and nothing
            // else: not a project's ic_quickaction_<name> anywhere, not a file in the
            // launcher module even under our prefix (the writer never goes there),
            // not a file without our prefix.
            WriteManifest(launcher: true);
            RunPostProcessor();
            var stalePng = Path.Combine(ResDir, "drawable-xhdpi", BuiltInPrefix + "add.png");
            var staleWebp = Path.Combine(ResDir, "drawable-xxhdpi", BuiltInPrefix + "play.webp");
            var inLauncherOurPrefix = LauncherDrawable("drawable", BuiltInPrefix + "play.xml");
            var theirsInOurModule = Path.Combine(ResDir, "drawable-xhdpi", "ic_quickaction_add.png");
            var theirsNested = ProjectDrawable("MyIcons.androidlib", "drawable-xhdpi", "ic_quickaction_play.png");
            var theirsInLauncher = LauncherDrawable("drawable", "ic_quickaction_search.png");
            var hostFile = Path.Combine(DrawableDir, "host_logo.png");
            foreach (var ours in new[] { stalePng, staleWebp })
                WriteFile(ours, new byte[] { 9 });
            foreach (var theirs in new[] { inLauncherOurPrefix, theirsInOurModule, theirsNested, theirsInLauncher, hostFile })
                WriteFile(theirs, UserBytes);
            foreach (var entry in QuickActionsBuiltInIcons.Entries)
                Assume.That(File.Exists(OurIcon(entry.Name)), "precondition: the post-processor wrote " + entry.Name);

            QuickActionsTrampolineStripperAndroid.Strip(UnityLibrary);

            foreach (var entry in QuickActionsBuiltInIcons.Entries)
                Assert.IsFalse(File.Exists(OurIcon(entry.Name)), "the built-in icon must be stripped: " + entry.Name);
            Assert.IsFalse(File.Exists(stalePng), "a stale built-in in another bucket and format is ours too");
            Assert.IsFalse(File.Exists(staleWebp), "…whatever the extension");
            foreach (var theirs in new[] { inLauncherOurPrefix, theirsInOurModule, theirsNested, theirsInLauncher, hostFile })
                CollectionAssert.AreEqual(UserBytes, File.ReadAllBytes(theirs), "must survive the sweep: " + theirs);
        }
    }
}
