// Harness-only tests (same mechanism, and same reason for living under .verify/,
// as AndroidKeepRulesTests.cs: Editor/Android and Editor/NativeGate sit behind
// asmdefs a Unity test assembly cannot reference on every build target, so the
// real source files are compiled straight into the dotnet test assembly).
//
// What they pin. 0.5.0 makes IconType.{Add,Compose,Favorite,Play} render on
// Android with nothing added to the project: the build post-processor writes the
// built-in PNGs (QuickActionsBuiltInIcons, generated by tools~/gen_builtin_icons.py)
// into the generated Gradle project, and the Java bridge finds them by name. Two
// things regress SILENTLY here — a build that writes no icons is green and looks
// exactly like 0.4.x's blank squares, and a define-off build that leaves them
// behind ships package art in a production APK — so both ends are held here.
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using NUnit.Framework;
using EminDeniz99.QuickActions;
using EminDeniz99.QuickActions.Editor;
using EminDeniz99.QuickActions.Editor.NativeGate;

namespace EminDeniz99.QuickActions.Tests
{
    [TestFixture]
    public class AndroidBuiltInIconsTests
    {
        private string _root;

        [SetUp]
        public void CreateProject()
        {
            QuickActionsStaticBuild.ResetForTests();
            _root = Path.Combine(Path.GetTempPath(), "qa-icons-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(UnityLibrary);
        }

        [TearDown]
        public void RemoveProject()
        {
            QuickActionsStaticBuild.ResetForTests();
            try
            {
                if (Directory.Exists(_root))
                    Directory.Delete(_root, true);
            }
            catch (IOException)
            {
            }
        }

        private string UnityLibrary => Path.Combine(_root, "unityLibrary");

        private string DrawableDir => Path.Combine(UnityLibrary, "src", "main", "res",
            "drawable-" + QuickActionsBuiltInIcons.DensityQualifier);

        private string OurIcon(string name) => Path.Combine(DrawableDir, "ic_quickaction_" + name + ".png");

        private string ManifestPath => Path.Combine(UnityLibrary, "src", "main", "AndroidManifest.xml");

        private void WriteManifest(bool launcher)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(ManifestPath));
            var filter = launcher
                ? "      <intent-filter>\n" +
                  "        <action android:name=\"android.intent.action.MAIN\" />\n" +
                  "        <category android:name=\"android.intent.category.LAUNCHER\" />\n" +
                  "      </intent-filter>\n"
                : "";
            File.WriteAllText(ManifestPath,
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"\n" +
                "    package=\"com.example.app\">\n" +
                "  <application>\n" +
                "    <activity android:name=\"com.unity3d.player.UnityPlayerActivity\">\n" +
                filter +
                "    </activity>\n" +
                "  </application>\n" +
                "</manifest>\n");
        }

        private void RunPostProcessor() =>
            new QuickActionsBuildPostProcessorAndroid()
                .OnPostGenerateGradleAndroidProject(UnityLibrary);

        private static void WriteFile(string path, byte[] contents)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllBytes(path, contents);
        }

        // A project's own drawable, the shape the README's .androidlib recipe
        // produces once Unity has copied it into the export: NESTED under
        // unityLibrary (unityLibrary/<Name>.androidlib/src/main/res/…) — not a root
        // sibling, which is what Unity's own notifications package relies on too.
        private string ProjectDrawable(string module, string qualifier, string fileName) =>
            Path.Combine(UnityLibrary, module, "src", "main", "res", qualifier, fileName);

        private static readonly byte[] UserBytes = Encoding.ASCII.GetBytes("the project's own art");

        [Test]
        public void WritesEveryBuiltInIcon_ByteIdentical_WithNoStaticShortcuts()
        {
            // The dynamic-only project is the main case (see the keep-rule tests): a
            // consumer adding every shortcut through QuickActions.Add(...) still gets
            // its icons through the same name lookup, so the write must not hang off
            // the static set. And "written" means the source of truth, byte for byte
            // — a re-encoded or truncated file would still resolve by name and draw
            // garbage, or nothing.
            WriteManifest(launcher: true);

            RunPostProcessor();

            foreach (var entry in QuickActionsBuiltInIcons.Entries)
            {
                Assert.IsTrue(File.Exists(OurIcon(entry.Name)), "missing " + OurIcon(entry.Name));
                CollectionAssert.AreEqual(entry.Bytes, File.ReadAllBytes(OurIcon(entry.Name)),
                    "ic_quickaction_" + entry.Name + " must be the embedded PNG, unchanged");
            }
            Assert.AreEqual(QuickActionsBuiltInIcons.Entries.Length,
                Directory.GetFiles(DrawableDir).Length, "nothing else may be written there");
        }

        [Test]
        public void TheCatalogSubsetShipped_IsExactlyTheFourWithArt()
        {
            // The docs promise these four and say the other 25 need the consumer's
            // own drawable. Adding art is welcome — it changes this list AND the docs,
            // which is what this pin is for.
            CollectionAssert.AreEquivalent(
                new[] { IconType.Add, IconType.Compose, IconType.Favorite, IconType.Play },
                QuickActionsBuiltInIcons.Entries.Select(e => e.Icon).ToArray());
        }

        [Test]
        public void EveryEntry_IsAValidPngOfTheDeclaredSize()
        {
            // The bytes are generated and base64-embedded; a bad regeneration would
            // not fail to compile. Pin the PNG signature, the IHDR dimensions against
            // PixelSize, and RGBA (colour type 6) — a launcher given a non-PNG or an
            // opaque image would draw a square, which is the state 0.5.0 exists to end.
            foreach (var entry in QuickActionsBuiltInIcons.Entries)
            {
                var png = entry.Bytes;
                Assert.GreaterOrEqual(png.Length, 33, entry.Name + ": too short to be a PNG");
                CollectionAssert.AreEqual(new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A },
                    png.Take(8).ToArray(), entry.Name + ": PNG signature");
                Assert.AreEqual("IHDR", Encoding.ASCII.GetString(png, 12, 4), entry.Name + ": first chunk");
                Assert.AreEqual(QuickActionsBuiltInIcons.PixelSize, BigEndian(png, 16), entry.Name + ": width");
                Assert.AreEqual(QuickActionsBuiltInIcons.PixelSize, BigEndian(png, 20), entry.Name + ": height");
                Assert.AreEqual(8, png[24], entry.Name + ": bit depth");
                Assert.AreEqual(6, png[25], entry.Name + ": colour type must be RGBA (6)");
            }
        }

        private static int BigEndian(byte[] b, int at) =>
            (b[at] << 24) | (b[at + 1] << 16) | (b[at + 2] << 8) | b[at + 3];

        [Test]
        public void WritesIcons_EvenWithNoLauncherActivity()
        {
            // Same ordering pin as the keep rule: the icons are written BEFORE the
            // launcher discovery that can end the callback early. A project whose
            // launcher lives where this callback cannot see it still gets its icons.
            WriteManifest(launcher: false);
            RunPostProcessor();
            Assert.IsTrue(File.Exists(OurIcon("play")), "a non-launcher manifest must not skip the icons");

            File.Delete(ManifestPath);
            Directory.Delete(DrawableDir, true);
            RunPostProcessor();
            Assert.IsTrue(File.Exists(OurIcon("play")), "a module with no manifest must not skip the icons");
        }

        [Test]
        public void RunningTwice_LeavesTheSameFiles()
        {
            // Append builds and repeated exports re-run the callback into the same
            // tree; the write must be idempotent, not accumulate.
            WriteManifest(launcher: true);

            RunPostProcessor();
            var first = Directory.GetFiles(DrawableDir).OrderBy(f => f)
                .ToDictionary(f => f, File.ReadAllBytes);
            RunPostProcessor();
            var second = Directory.GetFiles(DrawableDir).OrderBy(f => f)
                .ToDictionary(f => f, File.ReadAllBytes);

            CollectionAssert.AreEqual(first.Keys, second.Keys);
            foreach (var pair in first)
                CollectionAssert.AreEqual(pair.Value, second[pair.Key], pair.Key + " changed on re-run");
        }

        [Test]
        public void AProjectDrawableOfTheSameName_WinsOverTheBuiltIn()
        {
            // Upgrade path. The README documented a .androidlib recipe before these
            // icons existed, so real projects ship their own ic_quickaction_play.png
            // in their own module. AGP resolves the clash by priority and unityLibrary
            // outranks its dependencies, so writing ours would silently replace
            // theirs; the package must not do that. Theirs
            // stays untouched, ours is not written for THAT name — and a copy of ours
            // left by an earlier build (before they added the module) is removed so it
            // cannot shadow theirs. The other three are still written.
            WriteManifest(launcher: true);
            var theirs = ProjectDrawable("MyIcons.androidlib", "drawable-xhdpi", "ic_quickaction_play.png");
            WriteFile(theirs, UserBytes);
            WriteFile(OurIcon("play"), new byte[] { 1, 2, 3 }); // stale, from a previous build

            RunPostProcessor();

            Assert.IsFalse(File.Exists(OurIcon("play")), "the built-in play icon must yield to the project's");
            CollectionAssert.AreEqual(UserBytes, File.ReadAllBytes(theirs), "the project's file must be untouched");
            foreach (var name in new[] { "add", "compose", "favorite" })
                Assert.IsTrue(File.Exists(OurIcon(name)), "the other built-ins must still be written: " + name);
        }

        [Test]
        public void AProjectDrawable_AtTheGradleRoot_AlsoCounts()
        {
            // Unity nests the copied .androidlib under unityLibrary today; a
            // settingsTemplate.gradle, or a future Unity, can put a module at the
            // root instead. Both shapes are "the project already has this drawable".
            WriteManifest(launcher: true);
            var theirs = Path.Combine(_root, "RootIcons.androidlib", "src", "main", "res", "drawable-xhdpi", "ic_quickaction_compose.png");
            WriteFile(theirs, UserBytes);

            RunPostProcessor();

            Assert.IsFalse(File.Exists(OurIcon("compose")), "a root-level module's drawable must win too");
            CollectionAssert.AreEqual(UserBytes, File.ReadAllBytes(theirs));
        }

        [Test]
        public void AProjectDrawable_ReachedOnlyThroughSettingsGradle_Counts()
        {
            // "Export Project" with "Symlink Sources" copies nothing: settings.gradle
            // points the module at the original folder under Assets/ via projectDir.
            // A scan of the export's directories alone would never see that module
            // and would silently overlay the project's art with ours.
            WriteManifest(launcher: true);
            var external = Path.Combine(_root, "elsewhere", "Assets", "Icons.androidlib");
            var theirs = Path.Combine(external, "src", "main", "res", "drawable-xhdpi", "ic_quickaction_play.png");
            WriteFile(theirs, UserBytes);
            File.WriteAllText(Path.Combine(_root, "settings.gradle"),
                "include ':launcher'\n" +
                "include ':unityLibrary'\n" +
                "include ':Icons.androidlib'\n" +
                "project(':Icons.androidlib').projectDir = new File('" + external.Replace("\\", "/") + "')\n");

            RunPostProcessor();

            Assert.IsFalse(File.Exists(OurIcon("play")), "a module reached only through settings.gradle must win");
            CollectionAssert.AreEqual(UserBytes, File.ReadAllBytes(theirs));
            Assert.IsTrue(File.Exists(OurIcon("add")), "unrelated built-ins are still written");
        }

        [Test]
        public void AProjectDrawable_CountsWhateverItsExtensionOrDensity()
        {
            // An <adaptive-icon> is an .xml under drawable-anydpi-v26; a WebP is a
            // .webp; a different density bucket is still the same resource NAME to
            // aapt2. All of them are "the project already has this drawable".
            WriteManifest(launcher: true);
            WriteFile(ProjectDrawable("Icons.androidlib", "drawable-anydpi-v26", "ic_quickaction_add.xml"), UserBytes);
            WriteFile(ProjectDrawable("Art.androidlib", "drawable-xxhdpi", "ic_quickaction_favorite.webp"), UserBytes);

            RunPostProcessor();

            Assert.IsFalse(File.Exists(OurIcon("add")), "an adaptive-icon .xml counts as the project's drawable");
            Assert.IsFalse(File.Exists(OurIcon("favorite")), "a .webp in another density counts too");
            Assert.IsTrue(File.Exists(OurIcon("play")));
            Assert.IsTrue(File.Exists(OurIcon("compose")));
        }

        [Test]
        public void Names_MatchTheIconTypeMember_AndTheJavaLookupTable()
        {
            // Three copies of each name: the IconType member (documented rule:
            // snake_case of the member), the generated C# entry, and the Java
            // ICON_NAMES table the runtime lookup indexes by the enum's integer. The
            // Java copy is read from the repository file, which is why this test is
            // harness-only. Drift between them is silent — the drawable is written
            // under one name and looked up under another.
            var java = File.ReadAllText(Path.Combine(RepoRoot(), "Plugins", "Android", "QuickActionsBridge.java"));
            var table = Regex.Match(java, @"ICON_NAMES\s*=\s*\{([^}]*)\}", RegexOptions.Singleline);
            Assert.IsTrue(table.Success, "could not find ICON_NAMES in QuickActionsBridge.java");
            var javaNames = Regex.Matches(table.Groups[1].Value, "\"([^\"]*)\"")
                .Cast<Match>().Select(m => m.Groups[1].Value).ToArray();

            foreach (var entry in QuickActionsBuiltInIcons.Entries)
            {
                Assert.AreEqual(SnakeCase(entry.Icon.ToString()), entry.Name,
                    "the generated name must follow IconType's documented snake_case rule");
                Assert.AreEqual(javaNames[(int)entry.Icon], entry.Name,
                    $"ICON_NAMES[{(int)entry.Icon}] in QuickActionsBridge.java disagrees with the generated name");
            }
        }

        private static string SnakeCase(string member)
        {
            var sb = new StringBuilder();
            for (var i = 0; i < member.Length; i++)
            {
                if (i > 0 && char.IsUpper(member[i]))
                    sb.Append('_');
                sb.Append(char.ToLowerInvariant(member[i]));
            }
            return sb.ToString();
        }

        // Walk up from the test binary until the package root (the one directory
        // holding both package.json and Plugins/). The harness always runs from a
        // checkout; a miss is a broken harness, not a skip.
        private static string RepoRoot()
        {
            var dir = new DirectoryInfo(TestContext.CurrentContext.TestDirectory);
            while (dir != null)
            {
                if (File.Exists(Path.Combine(dir.FullName, "package.json")) &&
                    Directory.Exists(Path.Combine(dir.FullName, "Plugins")))
                    return dir.FullName;
                dir = dir.Parent;
            }
            throw new InvalidOperationException("package root not found above " + TestContext.CurrentContext.TestDirectory);
        }

        [Test]
        public void Stripper_RemovesTheBuiltInIcons_AndNothingAProjectOwns()
        {
            // The define-off cleanup runs in a production build; a reused/exported
            // project must come out of it carrying no package art. It sweeps by prefix
            // inside the two GENERATED modules — which is only safe because nothing
            // else writes that prefix there — and must never reach a project's own
            // .androidlib, nor a file in the generated module that is not ours.
            WriteManifest(launcher: true);
            RunPostProcessor();
            var launcherCopy = Path.Combine(_root, "launcher", "src", "main", "res", "drawable-xhdpi", "ic_quickaction_add.png");
            var hostFile = Path.Combine(DrawableDir, "host_logo.png");
            var theirs = ProjectDrawable("MyIcons.androidlib", "drawable-xhdpi", "ic_quickaction_play.png");
            WriteFile(launcherCopy, new byte[] { 9 });
            WriteFile(hostFile, UserBytes);
            WriteFile(theirs, UserBytes);
            foreach (var entry in QuickActionsBuiltInIcons.Entries)
                Assume.That(File.Exists(OurIcon(entry.Name)), "precondition: the post-processor wrote " + entry.Name);

            QuickActionsTrampolineStripperAndroid.Strip(UnityLibrary);

            foreach (var entry in QuickActionsBuiltInIcons.Entries)
                Assert.IsFalse(File.Exists(OurIcon(entry.Name)), "the built-in icon must be stripped: " + entry.Name);
            Assert.IsFalse(File.Exists(launcherCopy), "the launcher module is generated too and must be swept");
            Assert.IsTrue(File.Exists(hostFile), "a file without our prefix in the generated module is not ours");
            CollectionAssert.AreEqual(UserBytes, File.ReadAllBytes(theirs),
                "a project's .androidlib — nested under unityLibrary, where Unity puts it — is never touched");
        }
    }
}
